// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpicafftpmzlbvsxcgcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwaWNhZmZ0cG16bGJ2c3hjZ2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODY1MzYsImV4cCI6MjA2MjE2MjUzNn0.Zxvf6m5BUgqx1i0ihxJsw06Rzq3CqKrVliVJdUSjHqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);